### ISSUE TITLE
Install generator fails if project has an `Account` model

### ISSUE THREAD

**Issue by stevegeek** [SpinaCMS/Spina#377]
It looks like if a Rails project already has a model named `Account` then during `rails g spina:install` the project `Account` model is resolved instead of `::Spina::Account`.

```
	 3: from  .rvm/gems/ruby-2.5.1/gems/spina-1.0.1/lib/generators/spina/install_generator.rb:34:in `create_account'
	 2: from .rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:415:in `update_attribute'
	 1: from .rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:415:in `public_send'
.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_methods.rb:430:in `method_missing': undefined method `name=' for #<Account:0x00007fb2aa8f12b8> (NoMethodError)
```

I modified the `install_generator` to use `::Spina::Account` and I could complete the setup

**Comment by Bramjetten** [comment]
Thanks for figuring that out!
Could you create a PR for this?

**Comment by stevegeek** [comment]
Sure! I'll try look at that this week

**Comment by dankmitchell** [comment]
Please close this issue. #391 solved it
