### ISSUE TITLE
undefined method `jsonb' occured when I execute rails g spina:install

### ISSUE THREAD

**Issue by tackeyy** [SpinaCMS/Spina#378]
Thanks for great CMS :)

` undefined method jsonb ` occurred when I execute ` rails g spina:install ` , so I report it.

```
rails 5.2.0
spina 1.0.3
db MySQL
```

```
-- create_table(:spina_settings, {:options=>"ENGINE=InnoDB", :id=>:integer})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `jsonb' for #<ActiveRecord::ConnectionAdapters::MySQL::TableDefinition:0x007f849e28e8d8>
/Users/tackeyy/dev/spina_sample/db/migrate/20180623121812_create_spina_settings.spina.rb:6:in `block in change'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration/compatibility.rb:76:in `block in create_table'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:305:in `create_table'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:871:in `block in method_missing'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `block in say_with_time'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `say_with_time'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:860:in `method_missing'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration/compatibility.rb:34:in `create_table'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration/compatibility.rb:75:in `create_table'
/Users/tackeyy/dev/spina_sample/db/migrate/20180623121812_create_spina_settings.spina.rb:4:in `change'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:814:in `exec_migration'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:797:in `block in migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:796:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:977:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1345:in `ddl_transaction'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1262:in `each'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1210:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1036:in `up'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1011:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
NoMethodError: undefined method `jsonb' for #<ActiveRecord::ConnectionAdapters::MySQL::TableDefinition:0x007f849e28e8d8>
/Users/tackeyy/dev/spina_sample/db/migrate/20180623121812_create_spina_settings.spina.rb:6:in `block in change'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration/compatibility.rb:76:in `block in create_table'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:305:in `create_table'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:871:in `block in method_missing'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `block in say_with_time'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:840:in `say_with_time'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:860:in `method_missing'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration/compatibility.rb:34:in `create_table'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration/compatibility.rb:75:in `create_table'
/Users/tackeyy/dev/spina_sample/db/migrate/20180623121812_create_spina_settings.spina.rb:4:in `change'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:814:in `exec_migration'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:797:in `block in migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:796:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:977:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1345:in `ddl_transaction'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1262:in `each'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1210:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1036:in `up'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/migration.rb:1011:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/Users/tackeyy/dev/spina_sample/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by emilslv** [comment]
That's because of Mysql. Spina CMS is developed to work with Postgresql.

**Comment by tackeyy** [comment]
Thank you for reply. I got it and I found the document.
https://www.spinacms.com/guide/getting-started/prerequisites#main

**Comment by joeswann** [comment]
For anyone else that finds this, you might be able to use mysql version 9 and adjust the migration to use `json` instead of `jsonb`. 

I haven't thoroughly tested it yet but it seems to be just about the only hard reliance on postgres so far.

**Comment by Bramjetten** [comment]
While this is true for Spina CMS, Spina Shop relies more heavily on Postgres.
