### ISSUE TITLE
Failed to install spina

### ISSUE THREAD

**Issue by ipetrovski3** [SpinaCMS/Spina#661]
`rails g spina:install`

`
../config/initializers/mobility.rb:2:in `block in <main>': undefined method `default_backend=' for #<Class:0x00007fecc613b478> (NoMethodError)
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mobility-1.1.0/lib/mobility.rb:119:in `configure'
	from /Users/ipetrovski/Projects/myshop/config/initializers/mobility.rb:1:in `<main>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:326:in `block in load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:326:in `load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/notifications.rb:205:in `instrument'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:680:in `load_config_initializer'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:633:in `each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:32:in `run'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:50:in `each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `call'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/application.rb:384:in `initialize!'
	from /Users/ipetrovski/Projects/myshop/config/environment.rb:5:in `<main>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:332:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
 ✘ ipetrovski@Igors-MacBook-Pro  ~/Projects/myshop   master ±  rails g spina:install
/Users/ipetrovski/Projects/myshop/config/initializers/mobility.rb:2:in `block in <main>': undefined method `default_backend=' for #<Class:0x00007fac987cac58> (NoMethodError)
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mobility-1.1.0/lib/mobility.rb:119:in `configure'
	from /Users/ipetrovski/Projects/myshop/config/initializers/mobility.rb:1:in `<main>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:326:in `block in load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:326:in `load'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/notifications.rb:205:in `instrument'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:680:in `load_config_initializer'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:633:in `each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:32:in `run'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:50:in `each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `call'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.2.1/lib/rails/application.rb:384:in `initialize!'
	from /Users/ipetrovski/Projects/myshop/config/environment.rb:5:in `<main>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.2.1/lib/active_support/dependencies.rb:332:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ipetrovski/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'`

**Comment by Bramjetten** [comment]
Try using the latest version using the master branch.
